Service design
katiasuya/audio-conversion-service pull request #1
Opened 2021-02-02 20:53 UTC by katiasuya

2021-02-03 11:19 UTC, papahmsolo requested changes
Looks very good!

- We're converting audio files not necessarily songs
- We'll use Postgres as a DB, my bad I forgot to tell you
- Let's think about what entity is `converted` really (we can rename endpoints and a table)
- How do I download an original audio file and converted one? Where do I get this info from?
- Statuses

2021-02-04 10:59 UTC, katiasuya commented
> * How do I download an original audio file and converted one? Where do I get this info from?

I think we can obtain the place where the user can download his audios from the bucket  with the formula /{User.username}/{Audio.name}.{Audio.format} when needed, so there is no need to save the path in DB, and for me it doesn't make sense either to have the bucket name in the database as it will be always the same for all audios.

2021-02-04 12:39 UTC, papahmsolo commented
> /{User.username}/{Audio.name}.{Audio.format}

What happens if I have the same audio file name and type? Also, there's no Object storage and bucket for local development. So we need to know something about how to download the file.

2021-02-05 08:50 UTC, papahmsolo requested changes
Looks good!

-  Great job grouping endpoints by domain, but `/audios/request` is about a different entity, it's not about audio files, right?
- Let's make `Format` and `Status` enums, we won't need the tables for them then.
- Let's rename `creation` to `created` and also add `updated` for records that can be updated.
- Let's change ids to UUID 
- We still need to have a reference to the image in the storage somewhere in the DB

2021-02-08 08:27 UTC, papahmsolo requested changes
Looks very good!

**DB script**
- `updated` is not nullable, it's just the same as `created` upon record creation.
- there could be a problem with time zones, so let's make `timestamp` independent from time zone.
- let's think about what default value we'd like our timestamps to have? 
- is request status nullable?
- probably the most important question: how do I get all my conversion requests? Try to write a query for that. 

**Endpoint**
Given the requirements, we probably won't need as many endpoints, but if you want to implement them I'm okay with this. Just let's think of the endpoints naming, maybe we can come up with more precise names.

Last but not least, don't forget to update the README :)

2021-02-08 20:52 UTC, katiasuya commented
> * probably the most important question: how do I get all my conversion requests? Try to write a query for that.

We can do it joining the tables this way: 
request.original_id=audio.id
audio.user_id=user.id

I've already written the queries, they all work fine:)

2021-02-09 14:52 UTC, papahmsolo requested changes
Cool!

- [x] `POST /requests/{id}` do we know the ID before we create the request ?:)
- [x] It's okay for now but later on, we'll need a way to authenticate a user, so we'll have to add it.
- [ ] Which endpoint is responsible for the conversion?

2021-02-09 14:52 UTC, papahmsolo commented on README.md
> +First, download PostgreSQL server, install it on your system and run it.
What version?

2021-02-09 14:52 UTC, papahmsolo commented on scripts/schema.sql
> +status status DEFAULT 'queued',
Not sure if default works well here, I think we should explicitly set the status. but the status cannot be NULL

2021-02-09 16:17 UTC, katiasuya commented on scripts/schema.sql
> +status status DEFAULT 'queued',
I put not null in the architecture diagram but not in the code, my bad :(

2021-02-09 18:55 UTC, katiasuya commented
> * [ ]  Which endpoint is responsible for the conversion?
I think the conversion will be triggered in POST method of /requests endpoint.

2021-02-11 06:23 UTC, papahmsolo requested changes
Looks very good!

- [x] We can discuss the endpoint offline
- [x] We need to create a DB user in Postgres for the services, as we cannot use admin credentials for that, and it's better be in the script as well.

2021-02-11 06:23 UTC, papahmsolo commented on scripts/queries.sql
> +    ('61e72557-e5af-4bc2-b19e-b1e4c7820d14','song name', 'MP3', 'location');
You may want to obtain the id of the newly created record, you'll need this in the request record

2021-02-11 06:23 UTC, papahmsolo commented on scripts/queries.sql
> +   -- to create a user
You'll also need to select the user for login

2021-02-12 08:56 UTC, katiasuya commented on scripts/queries.sql
> +   -- to create a user
Do you mean comparing passwords for a particular username?

2021-02-15 07:50 UTC, papahmsolo requested changes
Looks very good!

2021-02-15 07:50 UTC, papahmsolo commented on scripts/schema.sql
> +END$$;
Storing credentials in the repo is a huge security breach, you should rather prompt to enter the user/password after you run the script.

2021-02-15 07:50 UTC, papahmsolo commented on scripts/queries.sql
> +    WHERE username = 'aaa';
Not really an issue, but it does not make sense to use the alias in such short queries.

2021-02-17 10:07 UTC, papahmsolo requested changes
Cool!

2021-02-17 10:07 UTC, papahmsolo commented on README.md
> +`scripts/create_db.sh`.
You'll probably get an error if you run the script from the root folder, you need to `cd scripts` first

2021-02-17 10:07 UTC, papahmsolo commented on scripts/create_db.sh
> +	-f schema.sql
- I think you need to run all the command as the DB admin, by default it asked me for a domain user password but should ask for `postgres` user password
- new line at the end of the file :)

2021-02-17 10:07 UTC, papahmsolo commented on scripts/create_db.sh
> +read  DB_PASSWORD
`-s` - do not echo password coming from a terminal

2021-02-18 08:44 UTC, papahmsolo approved these changes

2021-02-18 08:44 UTC, merged