Add handlers and routing
katiasuya/audio-conversion-service pull request #3
Opened 2021-02-22 16:05 UTC by katiasuya

2021-02-24 08:11 UTC, papahmsolo requested changes
- request/response types
- respond and respondErr helpers

2021-02-24 08:11 UTC, papahmsolo commented on internal/app/handlers.go
> +	}
We'll be validating this with JWT

2021-02-28 14:24 UTC, katiasuya commented on internal/app/handlers.go
> +	}
Okay

2021-02-28 21:29 UTC, katiasuya commented on internal/app/handlers.go
> +}
Done

2021-03-01 10:16 UTC, papahmsolo requested changes
Okay, it's fine for now, but let's keep in mind that the `app` package contains things that can be broken into multiple packages. Respond is dealing with sending general responses, `app` has the router for the services, etc.

2021-03-01 10:16 UTC, papahmsolo commented on internal/app/audio.go
> +}
`File` is not a string, is it? And the `name` you can get from the file header. But you need the source and target formats for conversion, right?

2021-03-03 17:56 UTC, papahmsolo approved these changes

2021-03-03 17:56 UTC, papahmsolo commented on internal/handler/conversion.go
>  	format := fileParts[1]
this will panic (index out of range) if there will be no extension in the file. I think you can get the format using content type in the header

2021-03-03 17:56 UTC, merged