Add tests
katiasuya/audio-conversion-service pull request #33
Opened 2021-07-08 08:40 UTC by katiasuya

2021-07-26 07:29 UTC, papahmsolo requested changes
Tests look good!

It's a matter of taste but `queries.go` does not contain only queries, so it can live inside `repository.go`

2021-07-26 07:29 UTC, papahmsolo commented on internal/repository/model/models.go
> +package model
Not sure if we it makes sense to separate model, but even if it does, it probably don't deserve a dedicated package

2021-07-26 07:29 UTC, papahmsolo commented on internal/repository/model/models.go
> +type User struct {
Comments?

2021-07-26 07:29 UTC, papahmsolo commented on internal/storage/storage.go
> +	fileID := uuid.NewString()
We probably can leave it like this, but this method could panic

2021-07-26 07:29 UTC, papahmsolo commented on internal/repository/queries_test.go
> +		},
Let's add another case or modify the existing test to handle more than one conversion request, you can also test some NULL values returned from DB

2021-07-26 07:29 UTC, papahmsolo commented on internal/repository/queries_test.go
> +			}
We can match all expected conversion requests against the returned ones

2021-07-26 08:15 UTC, katiasuya commented on internal/repository/model/models.go
> +package model
You're right, with the current architecture of the project it's not necessary anymore.

2021-07-26 09:12 UTC, katiasuya commented on internal/storage/storage.go
> +	fileID := uuid.NewString()
My bad, I didn't notice that in the description.

2021-07-26 11:12 UTC, katiasuya commented on internal/repository/queries_test.go
> +		},
The only value that doesn't have "NOT NULL" constraint is targetID and it's not included in request history.

2021-07-28 04:16 UTC, papahmsolo approved these changes

2021-07-28 04:16 UTC, merged