Connect database
katiasuya/audio-conversion-service pull request #5
Opened 2021-03-04 07:12 UTC by katiasuya

2021-03-08 14:13 UTC, katiasuya commented
Change application layout

2021-03-09 07:27 UTC, papahmsolo requested changes
Looks very good!

One note: in the handlers you can name your nested types as `request` and `response`, thus you will have the same name across all handlers.

2021-03-09 07:27 UTC, papahmsolo commented on internal/server/handlers.go
> +	}
In all of these cases let's return 400 with `invalid username or password`
https://stackoverflow.com/questions/14922130/which-error-message-is-better-when-users-entered-a-wrong-password

2021-03-09 07:27 UTC, papahmsolo commented on internal/server/handlers.go
> +	}
Shouldn't it be 500 in this case?

2021-03-09 07:27 UTC, papahmsolo commented on internal/repository/postgres.go
> +	return db, nil
You can simply `return db, err`

2021-03-09 07:27 UTC, papahmsolo commented on internal/repository/repository.go
> +	}
You'll need to create an error type for this error to distinguish between "no such user" and failed DB query in the handler

2021-03-09 07:49 UTC, katiasuya commented on internal/server/handlers.go
> +	}
I've handled this situation in InsertUser function as pq.Error

2021-03-10 07:35 UTC, papahmsolo requested changes
Looks good, let's fix some things

2021-03-10 07:35 UTC, papahmsolo commented on internal/repository/postgres.go
> +	return db, err
`return db, db.Ping()`

2021-03-10 07:35 UTC, papahmsolo commented on internal/repository/postgres.go
> +	return db, err
But your way is also fine

2021-03-10 07:35 UTC, papahmsolo commented on internal/server/handlers.go
> +	}
We shouldn't return anything but 401 in such cases 
https://stackoverflow.com/questions/14922130/which-error-message-is-better-when-users-entered-a-wrong-password

2021-03-10 07:35 UTC, papahmsolo commented on internal/server/handlers.go
> +	}
Not sure, why would download create files :)
Don't worry about it for now, we'll implement file storage in the next step

2021-03-10 07:35 UTC, papahmsolo commented on internal/repository/repository.go
> +	return hrs, err
same here: `return hrs, rows.Err()`

2021-03-10 07:52 UTC, papahmsolo approved these changes

2021-03-10 07:52 UTC, merged