Add logging
katiasuya/audio-conversion-service pull request #9
Opened 2021-04-06 04:57 UTC by katiasuya

2021-06-10 12:57 UTC, papahmsolo reviewed
👀🙌

2021-06-10 12:57 UTC, papahmsolo commented on internal/converter/converter.go
> +	}
Fatal is for main

2021-06-22 09:25 UTC, papahmsolo requested changes
Logging part looks good to me

2021-06-22 09:25 UTC, papahmsolo commented on internal/logger/logger.go
> +}
Is there a reason to make it exportable?

2021-06-22 09:25 UTC, papahmsolo commented on internal/server/handlers.go
> +)
What is the purpose of these error definitions? Are we handling these errors in any specific way?

2021-06-22 09:39 UTC, katiasuya commented on internal/server/handlers.go
> +)
I used to have various uses of this values, that's why I've created variables for them. But it's not necessary, you're right.

2021-06-22 12:16 UTC, papahmsolo approved these changes

2021-06-22 12:16 UTC, merged